"""
graph/nodes/sql_query.py
─────────────────────────
Node: sql_query

Handles questions that require SQL operations over structured (tabular) data
that was ingested from uploaded Excel / CSV files into SQLite.

Important limitations
─────────────────────
• Only Excel (.xlsx / .xls) files are ingested into SQLite. PDF documents —
  even those containing visual tables — are stored as plain text in ChromaDB.
  SQL aggregation is therefore NOT available for tables embedded in PDFs;
  those are answered via the vectorstore (text retrieval) path instead.
• If a user asks about numbers from a PDF (e.g. "total revenue" from an
  annual report), the router should send the question to vectorstore, where
  the LLM reads the extracted text and answers from it.
• This node is always followed by a vectorstore retrieve step (hybrid mode)
  so that even when SQL returns empty or partial results, PDF/text context
  is available to the generate node as a fallback.

Pipeline
────────
1.  Introspect available SQLite tables (schema + sample rows).
2.  Ask the LLM to write a SQLite-compatible SQL query for the user's question.
3.  Execute the query via structured_db.execute_sql().
4.  Format the results as a readable string and store them in state["sql_result"].
5.  Log every SQL query issued to state["sql_queries_used"].

The generate node then combines this structured result with any vector-store
context to produce the final natural-language answer.

Design notes
────────────
• The LLM is prompted with the full table schema AND a few sample rows so it
  can infer column types (e.g. date format, category values) without needing
  to ask follow-up questions.
• SQL generation uses structured output (Pydantic) so the query is always
  extracted cleanly — no regex parsing of LLM prose.
• The node is a no-op (returns empty sql_result) when no structured tables
  exist, so the rest of the graph degrades gracefully.
• Date arithmetic uses SQLite's strftime() function; the LLM is instructed
  to use this dialect explicitly.
"""

from __future__ import annotations

import logging
from typing import Optional

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

import config
from graph.state import GraphState
from structured_db import execute_sql, get_table_schemas, get_table_sample

log = logging.getLogger(__name__)


# ── Structured output schema ──────────────────────────────────────────────────

class SQLQueryPlan(BaseModel):
    """SQL query generated by the LLM for a structured-data question."""
    sql: str = Field(
        description="A valid SQLite SELECT query that answers the user's question. "
                    "Use only table and column names listed in the schema."
    )
    explanation: str = Field(
        description="One-sentence explanation of what the query computes."
    )


# ── Prompt ────────────────────────────────────────────────────────────────────

SQL_GEN_PROMPT = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are a SQLite expert. Given a database schema and sample data, \
write a single, correct SQLite SELECT query that answers the user's question.

Rules:
- Use ONLY the table and column names provided in the schema. Do not invent columns.
- For date filtering use SQLite strftime(), e.g.:
    strftime('%Y', Date) = '2024'
    strftime('%Y-%m', Date) = '2024-01'
- For aggregations use SUM(), COUNT(), AVG(), MIN(), MAX() as appropriate.
- Use GROUP BY when the question asks "by category", "per month", etc.
- Return at most 100 rows. Add LIMIT 100 if the query might return many rows.
- Do NOT use INSERT, UPDATE, DELETE, DROP, CREATE, or any DDL/DML.
- If the question cannot be answered with SQL from the available schema, \
  set sql to: SELECT 'No structured data available for this question' AS message

Available schema:
{schema}

Sample rows per table:
{samples}
""",
    ),
    ("human", "{question}"),
])


# ── LLM chain (built lazily) ──────────────────────────────────────────────────

_sql_gen_chain = None


def _build_sql_gen_chain():
    global _sql_gen_chain
    llm = ChatOpenAI(
        model=config.LLM_MODEL,
        temperature=0,
        openai_api_key=config.OPENAI_API_KEY,
    )
    _sql_gen_chain = SQL_GEN_PROMPT | llm.with_structured_output(SQLQueryPlan)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _build_schema_text(schemas: dict[str, list[str]]) -> str:
    lines = []
    for table, cols in schemas.items():
        lines.append(f"Table: {table}")
        lines.append("  Columns: " + ", ".join(cols))
    return "\n".join(lines) if lines else "No structured tables available."


def _build_sample_text(schemas: dict[str, list[str]]) -> str:
    parts = []
    for table in schemas:
        sample = get_table_sample(table, n=3)
        if sample:
            header = " | ".join(sample[0].keys())
            rows   = [" | ".join(str(v) for v in row.values()) for row in sample]
            parts.append(f"Table: {table}\n{header}\n" + "\n".join(rows))
    return "\n\n".join(parts) if parts else "No sample data."


def _format_sql_result(rows: list[dict], columns: list[str], max_rows: int = 50) -> str:
    """Format SQL query results as a readable plain-text table."""
    if not rows:
        return "The query returned no results."

    displayed = rows[:max_rows]
    col_widths = {c: max(len(c), max(len(str(r.get(c, ""))) for r in displayed))
                  for c in columns}

    header = " | ".join(c.ljust(col_widths[c]) for c in columns)
    sep    = "-+-".join("-" * col_widths[c] for c in columns)
    body   = "\n".join(
        " | ".join(str(r.get(c, "")).ljust(col_widths[c]) for c in columns)
        for r in displayed
    )

    result = f"{header}\n{sep}\n{body}"
    if len(rows) > max_rows:
        result += f"\n… ({len(rows) - max_rows} more rows not shown)"
    return result


# ── Node ──────────────────────────────────────────────────────────────────────

def sql_query(state: GraphState) -> GraphState:
    """
    LangGraph node — generate and execute a SQL query for structured-data questions.

    Input  state keys: question
    Output state keys: sql_result, sql_queries_used, steps
    """
    global _sql_gen_chain
    if _sql_gen_chain is None:
        _build_sql_gen_chain()

    steps           = state.get("steps", [])
    sql_queries_used: list[str] = state.get("sql_queries_used", [])

    # ── 1. Check for available tables ────────────────────────────────────────
    schemas = get_table_schemas()
    if not schemas:
        # No structured tables — skip SQL, let the downstream retrieve node handle it
        log.info("sql_query node: no structured tables found — skipping SQL, vectorstore will answer.")
        steps.append("sql_query_no_tables")
        return {
            "sql_result":       "",
            "sql_queries_used": sql_queries_used,
            "steps":            steps,
        }

    # ── 2. Generate SQL ───────────────────────────────────────────────────────
    schema_text = _build_schema_text(schemas)
    sample_text = _build_sample_text(schemas)
    question    = state["question"]

    try:
        plan: SQLQueryPlan = _sql_gen_chain.invoke({
            "schema":   schema_text,
            "samples":  sample_text,
            "question": question,
        })
        generated_sql = plan.sql.strip()
        log.info("SQL generated: %s", generated_sql)
    except Exception as e:
        log.exception("SQL generation failed")
        steps.append("sql_query_gen_failed")
        return {
            "sql_result":       f"Failed to generate SQL query: {e}",
            "sql_queries_used": sql_queries_used,
            "steps":            steps,
        }

    # ── 3. Execute SQL ────────────────────────────────────────────────────────
    try:
        rows, columns = execute_sql(generated_sql)
        sql_queries_used.append(generated_sql)
        log.info("SQL executed — %d row(s) returned.", len(rows))
    except Exception as e:
        log.exception("SQL execution failed: %s", generated_sql)
        sql_queries_used.append(f"-- FAILED: {generated_sql}")
        steps.append("sql_query_exec_failed")
        return {
            "sql_result":       f"SQL execution error: {e}\nQuery attempted:\n{generated_sql}",
            "sql_queries_used": sql_queries_used,
            "steps":            steps,
        }

    # ── 4. Format result ──────────────────────────────────────────────────────
    result_text = _format_sql_result(rows, columns)
    sql_result  = (
        f"SQL Query executed:\n```sql\n{generated_sql}\n```\n\n"
        f"Query explanation: {plan.explanation}\n\n"
        f"Results:\n{result_text}"
    )

    steps.append("sql_query")
    return {
        "sql_result":       sql_result,
        "sql_queries_used": sql_queries_used,
        "steps":            steps,
    }
